In [0]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# How to do slicing
print(a[1:5])

[1 2 3 4]


In [0]:
print(a[1:6:2])

[1 3 5]


In [0]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [0]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [0]:
#Fancy indexing or boolean indexing
print(a[a>5])

[6 7 8 9]


In [0]:
a.shape

(10,)

In [0]:
a.ndim

1

In [0]:
a1 = np.random.randint(10,30,(3,3))

In [0]:
a1


array([[21, 25, 22],
       [25, 22, 10],
       [21, 18, 17]])

In [0]:
a1.ndim

2

In [0]:
a1.shape

(3, 3)

In [0]:
for i in a1:
  print(i)
  break

[21 25 22]


In [0]:
for i in a1:
  for j in i:
    print(j,end=" ")
  print()

21 25 22 
25 22 10 
21 18 17 


In [0]:
print(a1[1:],type(a1[1:]),a1[1:].shape)

[[25 22 10]
 [21 18 17]] <class 'numpy.ndarray'> (2, 3)


In [0]:
print(a1[0],type(a1[0]),a1[0].shape)

[21 25 22] <class 'numpy.ndarray'> (3,)


In [0]:
#rows from 0 to 2
#cols from 0 to 3
#1st row and 2nd column
print(a1[1][2])
print(a1[1,2])

10
10


In [0]:
print(a1[1:3,0:2])

[[25 22]
 [21 18]]


In [0]:
print(a1)

[[21 25 22]
 [25 22 10]
 [21 18 17]]


In [0]:
print(a1[1::2,2])

[10]


In [0]:
print(a1[1::2,0:5:2])

[[25 10]]


In [0]:
a3 = np.random.randint(10,100,(5,5,3))
print(a3)

[[[23 38 93]
  [12 80 95]
  [53 31 44]
  [72 53 85]
  [32 17 88]]

 [[20 83 81]
  [76 27 86]
  [85 79 66]
  [49 94 67]
  [87 92 35]]

 [[79 20 19]
  [17 64 43]
  [61 36 54]
  [51 61 46]
  [60 60 14]]

 [[22 53 96]
  [90 18 77]
  [79 69 98]
  [66 40 61]
  [50 77 97]]

 [[22 51 98]
  [63 53 69]
  [58 34 58]
  [15 64 27]
  [90 29 59]]]


In [0]:
print(a3[:2])

[[[23 38 93]
  [12 80 95]
  [53 31 44]
  [72 53 85]
  [32 17 88]]

 [[20 83 81]
  [76 27 86]
  [85 79 66]
  [49 94 67]
  [87 92 35]]]


In [0]:
print(a3[::2])

[[[23 38 93]
  [12 80 95]
  [53 31 44]
  [72 53 85]
  [32 17 88]]

 [[79 20 19]
  [17 64 43]
  [61 36 54]
  [51 61 46]
  [60 60 14]]

 [[22 51 98]
  [63 53 69]
  [58 34 58]
  [15 64 27]
  [90 29 59]]]


In [0]:
print(a3[1:3,0:2])

[[[20 83 81]
  [76 27 86]]

 [[79 20 19]
  [17 64 43]]]


In [0]:
print(a3[1::2,2])

[[85 79 66]
 [79 69 98]]


In [0]:
print(a3[1::2,0:5:2])

[[[20 83 81]
  [85 79 66]
  [87 92 35]]

 [[22 53 96]
  [79 69 98]
  [50 77 97]]]


In [0]:
#boolean indexing
a3[a3==83]

array([83])

In [0]:
a3[a3>50]

array([93, 80, 95, 53, 72, 53, 85, 88, 83, 81, 76, 86, 85, 79, 66, 94, 67,
       87, 92, 79, 64, 61, 54, 51, 61, 60, 60, 53, 96, 90, 77, 79, 69, 98,
       66, 61, 77, 97, 51, 98, 63, 53, 69, 58, 58, 64, 90, 59])

In [0]:
a3[(a3>50)&(a3<70)]

array([53, 53, 66, 67, 64, 61, 54, 51, 61, 60, 60, 53, 69, 66, 61, 51, 63,
       53, 69, 58, 58, 64, 59])

In [0]:
a3[(a3>50)|(a3<70)]

array([23, 38, 93, 12, 80, 95, 53, 31, 44, 72, 53, 85, 32, 17, 88, 20, 83,
       81, 76, 27, 86, 85, 79, 66, 49, 94, 67, 87, 92, 35, 79, 20, 19, 17,
       64, 43, 61, 36, 54, 51, 61, 46, 60, 60, 14, 22, 53, 96, 90, 18, 77,
       79, 69, 98, 66, 40, 61, 50, 77, 97, 22, 51, 98, 63, 53, 69, 58, 34,
       58, 15, 64, 27, 90, 29, 59])

In [0]:
L = list(range(100))

In [0]:
L

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [0]:
aL = np.array(L)
aL[[1,13,56,74,32,54,12]]

array([ 1, 13, 56, 74, 32, 54, 12])

In [0]:
a1

array([[21, 25, 22],
       [25, 22, 10],
       [21, 18, 17]])

In [0]:
a1[[1,2],[0,1]] #(1,0)(2,1)

array([25, 18])

In [0]:
print(a3[[1,2],[1,2],[1,2]])#(1,1,1)(2,2,2)

[27 54]


In [0]:
print(a3[1,1,1])

27


In [0]:
print(a3[2,2,2])

54


In [0]:
#Statistical Functions
a = np.random.randint(20,30,5)
a

array([29, 25, 20, 26, 24])

In [0]:
print(np.mean(a)) #average
print(np.sum(a)/np.size(a))

24.8
24.8


In [0]:
# sorted a = [20,24,25,26,29]
np.median(a)

25.0

In [0]:
#Quantile
print(np.quantile(a,0.25)) #median value of 1st part Q1
print(np.quantile(a,0.5)) #median value of total points Q2
print(np.quantile(a,0.75)) #median value of last part Q3

24.0
25.0
26.0


In [0]:
#Logarithmic and Exponential
np.log(2) #log with base e

0.6931471805599453

In [0]:
print(np.log2(2)) #log with base 2
print(np.log10(2)) #log with base 10

1.0
0.3010299956639812


In [0]:
np.log(np.exp(1))

1.0

In [0]:
np.log(0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [0]:
np.log(0+1)

0.0

In [0]:
np.exp(1)

2.718281828459045

In [0]:
np.exp(2)

7.38905609893065