- classification
    - Binary
    - Multiclass
    - Sentiment Analysis
    - Anomly detection 
- Regression
- Recommender Systems
- Reinforcement Learning
- NLP
    - Q&A
    - Auto completion
    - Chatbot
- Computer Vision
    - Object detection
    - Object tracking
    - image classfication
    - image tagging
- Data
    - numerical data
    - image data
    - audio data
    - video data
    - text data
    - from documents
    - satellite imagery
    - timeseries data(Temperatue Reading, Stock prices)

- What are csv, tsv files?
- What are packages available to handle csv data?
- What is json format?
- How to handle json data?
- What are packages available for image data?
- What are the packages available for audio data?
- With all the packages above check how to read the data?
- How to display the same data?

In [ ]:
csv(comma seperated value),tsv(tab separated value) files
- 

Packages to handle csv data
- pandas 
- csv
- numpy

In [2]:
import pandas
path = "sample.csv"
csv_file = pandas.read_csv(path)
type(csv_file)

pandas.core.frame.DataFrame

In [3]:
csv_file

name  age  gender  salary  year
0             Ravi Ram   32    Male   72000  2016
1          Ravi Rajesh   28    Male   42000  2018
2         Surath Kumar   31    Male   32000  2019
3          Anil Arella   28    Male   62000  2016
4       Swetha Geetham   24  Female   52000  2017
5        Savita Rajesh   23  Female   31000  2019
6  Sravanthi Nandigama   26  Female   34000  2015

In [4]:
import csv
help(csv.reader)

Help on built-in function reader in module _csv:

reader(...)
    csv_reader = reader(iterable [, dialect='excel']
                            [optional keyword args])
        for row in csv_reader:
            process(row)
    
    The "iterable" argument can be any object that returns a line
    of input for each iteration, such as a file object or a list.  The
    optional "dialect" parameter is discussed below.  The function
    also accepts optional keyword arguments which override settings
    provided by the dialect.
    
    The returned object is an iterator.  Each iteration returns a row
    of the CSV file (which can span multiple input lines).



In [5]:
file = csv.reader(["i am, reka","machine,learning"])
for row in file:
    print(row)

['i am', ' reka']
['machine', 'learning']


In [12]:
f = open(path)
lines = csv.reader(f)
for row in lines:
    print(row)
#list(lines)

['name', 'age', 'gender', 'salary', 'year']
['Ravi Ram', '32', 'Male', '72000', '2016']
['Ravi Rajesh', '28', 'Male', '42000', '2018']
['Surath Kumar', '31', 'Male', '32000', '2019']
['Anil Arella', '28', 'Male', '62000', '2016']
['Swetha Geetham', '24', 'Female', '52000', '2017']
['Savita Rajesh', '23', 'Female', '31000', '2019']
['Sravanthi Nandigama', '26', 'Female', '34000', '2015']


In [ ]:
for line in sys.stdin:
    words = line.strip().split()
    print(" ".join([word.capitalize() for word in words]))

In [16]:
with open(path) as f:
    data = csv.DictReader(f)
    print(type(data))
    for row in data:
        print(row)

<class 'csv.DictReader'>
OrderedDict([('name', 'Ravi Ram'), ('age', '32'), ('gender', 'Male'), ('salary', '72000'), ('year', '2016')])
OrderedDict([('name', 'Ravi Rajesh'), ('age', '28'), ('gender', 'Male'), ('salary', '42000'), ('year', '2018')])
OrderedDict([('name', 'Surath Kumar'), ('age', '31'), ('gender', 'Male'), ('salary', '32000'), ('year', '2019')])
OrderedDict([('name', 'Anil Arella'), ('age', '28'), ('gender', 'Male'), ('salary', '62000'), ('year', '2016')])
OrderedDict([('name', 'Swetha Geetham'), ('age', '24'), ('gender', 'Female'), ('salary', '52000'), ('year', '2017')])
OrderedDict([('name', 'Savita Rajesh'), ('age', '23'), ('gender', 'Female'), ('salary', '31000'), ('year', '2019')])
OrderedDict([('name', 'Sravanthi Nandigama'), ('age', '26'), ('gender', 'Female'), ('salary', '34000'), ('year', '2015')])


In [17]:
with open(path) as f:
    data = csv.DictReader(f)
    print(type(data))
    for row in data:
        print(row['salary'])

<class 'csv.DictReader'>
72000
42000
32000
62000
52000
31000
34000


In [29]:
with open(path) as f:
    data = csv.DictReader(f)
    print(type(data))
    for row in data:
        row = list(row.items())
        #print(row)
        print(row)

<class 'csv.DictReader'>
[('name', 'Ravi Ram'), ('age', '32'), ('gender', 'Male'), ('salary', '72000'), ('year', '2016')]
[('name', 'Ravi Rajesh'), ('age', '28'), ('gender', 'Male'), ('salary', '42000'), ('year', '2018')]
[('name', 'Surath Kumar'), ('age', '31'), ('gender', 'Male'), ('salary', '32000'), ('year', '2019')]
[('name', 'Anil Arella'), ('age', '28'), ('gender', 'Male'), ('salary', '62000'), ('year', '2016')]
[('name', 'Swetha Geetham'), ('age', '24'), ('gender', 'Female'), ('salary', '52000'), ('year', '2017')]
[('name', 'Savita Rajesh'), ('age', '23'), ('gender', 'Female'), ('salary', '31000'), ('year', '2019')]
[('name', 'Sravanthi Nandigama'), ('age', '26'), ('gender', 'Female'), ('salary', '34000'), ('year', '2015')]


#### List Comprehensions

In [39]:
l1 = [1,2,3,4,24]
l2 = [3,4,5,6,3]

In [40]:
add_list = [l1[i]+l2[i] for i in range(len(l1))]

In [41]:
add_list

[4, 6, 8, 10, 27]

In [51]:
#get the numbers which are not multiple of 3 as a list using listcomprehension
out =[i for i in add_list if i%3!=0]

In [52]:
out

[4, 8, 10]

In [49]:
#replace the multiples of 3 with -1
out = [i if i%3!=0 else -1 for i in add_list]

In [50]:
out

[4, -1, 8, 10, -1]

In [53]:
out.extend([1,2,3,4,5])
out

[4, 8, 10, 1, 2, 3, 4, 5]

In [56]:
#replace multiples of 2 with -2
#replace multiples of 3 with -1
#If it is a multiple of both replace it with -2
out1 = []
for i in out:
    if i%2==0:
        out1.append(-2)
    elif i%3==0:
        out1.append(-1)
    else: 
        out1.append(i)
print(out1)
print(out)

[-2, -2, -2, 1, -2, -1, -2, 5]
[4, 8, 10, 1, 2, 3, 4, 5]


In [61]:
out2 = [-2 if i%2==0 else -1 if i%3==0 else i for i in out]
out2

[-2, -2, -2, 1, -2, -1, -2, 5]

#### List Comprehension with Nested for

In [62]:
l1,l2

([1, 2, 3, 4, 24], [3, 4, 5, 6, 3])

In [63]:
numbers = [(i,j) for i in l1 for j in l2]
numbers

[(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 3),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 3),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 3),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 3),
 (24, 3),
 (24, 4),
 (24, 5),
 (24, 6),
 (24, 3)]

In [79]:
l2 = [[23,45],[78,98],[34,12]]
out_l2 = [j for i in l2 for j in i]
out_l2

[23, 45, 78, 98, 34, 12]

In [78]:
out = []
for i in l2:
    for j in i:
        out.append(j)
out

[23, 45, 78, 98, 34, 12]

In [84]:
#common elements in two lists using list comprehension
l1 = list(range(5,20,2))
l2 = list(range(1,20,2))
print(l1)
print(l2)
out = []
for i in l1:
    for j in l2:
        if i==j:
            print(i) 
#out

[5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
5
7
9
11
13
15
17
19


In [83]:
out = [j for i in l1 for j in l2 if i==j]
out

[5, 7, 9, 11, 13, 15, 17, 19]

### Numpy
- numerical python
- vectorized programming
- handling multidimensional data
- Manipulating Arrays
- We can define the datatype
- Commonly used with numerical data. But it may use mixed data as well
- Faster execution
- Less memory
- Most of the mathematical functions are available
    - linear algebra
    - statistics
    - probability
    - Fourier transforms
    - Trignometric
    - Logarithms


In [85]:
import numpy
numpy.__version__ #attribute "__"-dunder

'1.18.1'

In [86]:
#importing a package with alias name
import numpy as np

#### converting existing data into numpy array

In [91]:
l = [9,8,57,3,4]
np_array = np.array(l)
print(np_array)
type(np_array)

[ 9  8 57  3  4]


numpy.ndarray

In [92]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [93]:
t = (2,4,5,6,7)
array_t = np.array(t)
print(array_t)
type(array_t)

[2 4 5 6 7]


numpy.ndarray

In [96]:
d = {'name':'ravi','age':30,'salary':50000}
array_d = np.array(d)
print(array_d)
type(array_d)

{'name': 'ravi', 'age': 30, 'salary': 50000}


numpy.ndarray

In [97]:
a1 = np.array(6)
print(a1)
type(a1)

6


numpy.ndarray

In [98]:
array_values = np.array(list(d.values()))
print(array_values)

['ravi' '30' '50000']


#### Initializing Arrays

In [99]:
np.zeros(3)

array([0., 0., 0.])

In [100]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
array_zeros = np.zeros((3,3))
print(array_zeros.dtype)
print(type(array_zeros.dtype))

float64
<class 'numpy.dtype'>


In [103]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [105]:
array_zeros = np.zeros((3,3),dtype=int)
print(array_zeros.dtype)
print(type(array_zeros.dtype))
print(array_zeros)

int32
<class 'numpy.dtype'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [106]:
array_ones = np.ones((3,3),dtype=int)
print(array_ones.dtype)
print(type(array_ones.dtype))
print(array_ones)

int32
<class 'numpy.dtype'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [108]:
array_bool = np.ones((3,3),dtype=bool)
print(array_bool.dtype)
print(type(array_bool.dtype))
print(array_bool)

bool
<class 'numpy.dtype'>
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [109]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [110]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Creating Arrays with in a specific range

In [113]:
print(np.arange(6))
print(np.arange(1,6))
print(np.arange(1,6,2))
print(np.arange(1,6,0.5))
print(np.arange(-1,6,0.5))

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]
[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5]


In [116]:
print(np.linspace(1,5,10))
print(np.arange(1,5,3))
print(np.arange(1,6,2))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1 4]
[1 3 5]


In [120]:
np.random.randint(10)

3

In [121]:
np.random.randint(10,size=(2,3))

array([[2, 7, 4],
       [3, 0, 5]])

In [123]:
np.random.randint(10,34,size=(2))

array([29, 20])

In [124]:
multi_array = np.random.randint(1,1000,size=(10,10))
multi_array

array([[979, 858, 636, 111, 767,  28, 130, 503, 142, 297],
       [446, 567, 324, 787, 377, 778, 541,  44, 535, 529],
       [ 51, 308, 925, 863, 889, 698, 592, 883, 336, 947],
       [946, 569, 193, 536, 641, 140, 758, 499, 710,   7],
       [999, 984, 876, 234, 485, 628, 841, 237, 619,  50],
       [ 44, 893, 441, 247, 650, 429, 671, 482, 537,  84],
       [118, 350, 566, 135,  85, 231, 795, 916, 846,  49],
       [241, 600, 737, 894, 536, 110, 222, 792, 775, 802],
       [677, 431, 963, 832, 319, 269, 918, 598, 339, 378],
       [630, 725, 264,  87, 933, 589, 991, 918, 970, 831]])

In [126]:
array_ones,array_zeros

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]), array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [128]:
print(array_ones.dtype)# data type of the array
print(array_ones.shape) # shape as a tuple
print(array_ones.ndim) #no of dimensions
print(array_ones.size) #no of items in the array
print(array_ones.itemsize)# size in bytes
print(array_ones.imag)
print(array_ones.nbytes) #itemsize * no of items

int32
(3, 3)
2
9
4
[[0 0 0]
 [0 0 0]
 [0 0 0]]
36


In [129]:
t = (5,)
print(t,type(t))

(5,) <class 'tuple'>


#### Updating the values in an array

In [134]:
array1 = [2,3,4]
array_1d = np.array(array1)

In [135]:
array_1d

array([2, 3, 4])

In [136]:
array_1d[0] = 9
array_1d

array([9, 3, 4])

In [137]:
#check for loop with 1d and 2d arrays
for i in array_1d:
    print(i)
    break

9


In [138]:
for i in array_zeros:
    print(i)
    break

[0 0 0]


#### Mathematical Operators

In [141]:
a = np.arange(10)
b = np.arange(10,20)
print(a+b)
print(a-b)
print(a%b)
print(a/b)
print(a//b)
print(a*b)
print(b**2)

[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[0 1 2 3 4 5 6 7 8 9]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
[0 0 0 0 0 0 0 0 0 0]
[  0  11  24  39  56  75  96 119 144 171]
[100 121 144 169 196 225 256 289 324 361]


In [142]:
print(a>5)
print(a==5)
print(a<5)

[False False False False False False  True  True  True  True]
[False False False False False  True False False False False]
[ True  True  True  True  True False False False False False]
