Import numpy as np and print the version number.

In [1]:
import numpy as np
print(np.__version__)

1.18.1


Create a 1D array of numbers from 0 to 9

In [2]:
array1 = np.arange(9)
print(array1)

[0 1 2 3 4 5 6 7 8]


In [6]:
print(array1.ndim)

1


In [8]:
print(type(array1))

<class 'numpy.ndarray'>


Create a 3×3 numpy array of all True’s

In [3]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [14]:
#arange([start,] stop[, step,], dtype=None)
array2 = np.ones([3,3],dtype=bool)
print(array2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Extract all odd numbers from arr

In [31]:
array1 = np.arange(10)
new_array = [i for i in array1 if i%2!=0]
print(new_array)

[1, 3, 5, 7, 9]


Replace all odd numbers in arr with -1

In [32]:
array1 = np.arange(10)
new_array = [-1 if i%2!=0 else i for i in array1]
print(new_array)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


Convert a 1D array to a 2D array with 2 rows

In [43]:
array1d = np.array([1,2,3,4,5,6,7,8])

In [44]:
array1d.ndim

1

In [48]:
array2d = array1d.reshape(2,4)

In [50]:
print(array2d.ndim)
print(array2d)

2
[[1 2 3 4]
 [5 6 7 8]]


Stack arrays a and b vertically
> `a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)`

In [58]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally.

In [59]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Get the positions where elements of a and b match<br>

Input:<br>

> `a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])`

In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a, b))[0]

array([1, 3, 5, 7], dtype=int64)

Get all items between 5 and 10 from a.<br>

Input:<br>

>`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [74]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = a[(a>=5) & (a<=10)]
b

array([ 6,  9, 10])

<pre>Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])</pre>

In [75]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [82]:
import numpy as np
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

np.maximum(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [83]:
def maxx(x,y):
    if x>=y:
        return x
    return y
pair_max = np.vectorize(maxx)

In [84]:
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

<pre>swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr</pre

In [85]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
arr1 = np.arange(9).reshape(3,3)
arr1[:,[1,2]] = arr1[:,[2,1]]
print(arr1)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


<pre>How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)
arr</pre

In [89]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
reverse_arr = np.flip(arr)
reverse_arr

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

<pre>Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr</pre>

In [98]:
arr = np.arange(9).reshape(3,3)
print(arr,'\n')
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[6 7 8]
 [3 4 5]
 [0 1 2]]


Write a NumPy program to generate five random numbers from the normal distribution

In [100]:
x = np.random.normal(size=10)
x

array([-0.61000783, -0.78175158,  1.85012747,  0.25849931, -0.28198787,
        2.16850794, -0.70873116, -2.47035902, -3.10603573,  1.60150035])

Write a NumPy program to generate six random integers between 10 and 30

In [101]:
x = np.random.randint(10,30,6)
x

array([22, 18, 28, 19, 17, 19])

Write a NumPy program to create a 3x3x3 array with random values

In [103]:
x = np.random.random((3,3,3))
x

array([[[4.24402375e-02, 6.01138945e-01, 8.70563405e-01],
        [1.48096082e-02, 3.89021190e-02, 5.25612916e-04],
        [4.37834418e-01, 8.87650960e-01, 5.13869215e-01]],

       [[6.58093736e-01, 4.28496922e-01, 7.31066949e-03],
        [6.43566301e-01, 1.16313294e-01, 5.65843729e-01],
        [5.75259142e-01, 5.91871308e-01, 8.72553520e-01]],

       [[5.17720077e-01, 4.44733746e-01, 5.54440816e-01],
        [5.70168655e-01, 6.99707524e-01, 8.15329507e-01],
        [8.53921485e-01, 1.82718623e-01, 1.02217515e-01]]])

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [107]:
array = np.random.random((5,5))
array

array([[0.51680247, 0.26809649, 0.74324661, 0.64145717, 0.76766597],
       [0.50483596, 0.32748341, 0.01724312, 0.08482986, 0.28839458],
       [0.22517383, 0.87716264, 0.23328743, 0.69163129, 0.07254813],
       [0.15131921, 0.03566822, 0.27064754, 0.38238401, 0.79767852],
       [0.02851884, 0.04207711, 0.41373563, 0.97407064, 0.6598159 ]])

In [108]:
array.min()

0.017243120267027567

In [109]:
array.max()

0.9740706364245134

Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [111]:
array1 = np.random.random((10,4))
array1

array([[0.80787957, 0.49266901, 0.89944722, 0.17191138],
       [0.41288772, 0.07838177, 0.40092759, 0.17806607],
       [0.22363875, 0.12810308, 0.84701875, 0.44142426],
       [0.0554465 , 0.29959592, 0.40963717, 0.86711068],
       [0.30814896, 0.81087456, 0.59514909, 0.07004222],
       [0.89116785, 0.92958583, 0.25154358, 0.94402205],
       [0.50768992, 0.80132312, 0.66886112, 0.14005436],
       [0.36217415, 0.16967334, 0.09309601, 0.90413861],
       [0.20549144, 0.21280517, 0.05159365, 0.55097202],
       [0.411326  , 0.26808264, 0.69771731, 0.76275907]])

In [113]:
array1[:5,:]

array([[0.80787957, 0.49266901, 0.89944722, 0.17191138],
       [0.41288772, 0.07838177, 0.40092759, 0.17806607],
       [0.22363875, 0.12810308, 0.84701875, 0.44142426],
       [0.0554465 , 0.29959592, 0.40963717, 0.86711068],
       [0.30814896, 0.81087456, 0.59514909, 0.07004222]])

 Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [115]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.random.shuffle(x)
x

array([2, 8, 9, 0, 6, 7, 1, 4, 3, 5])

Read an JPEG image into a numpy array, return the size and shap of that image


In [126]:
from PIL import Image
from numpy import asarray
# load the image
image = Image.open('flower.jpg')
# convert image to numpy array
data = asarray(image)
print(type(data))
# shape
print(data.shape)
# size
print(data.size)

<class 'numpy.ndarray'>
(531, 800, 3)
1274400
